name: Deploy Vite App to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js (ensure the correct version for your project)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust this to match your Node.js version

    # Step 3: Install dependencies (using npm ci for clean install)
    - name: Install dependencies
      run: npm ci

    # Step 4: Build the Vite project
    - name: Build the project
      run: npm run build

    # Step 5: Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

